# my global config
global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/os-alerts.yml"
  - "rules/log-alerts.yml"

scrape_configs:
  - job_name: 'node'  # This is a default value, it is mandatory.
    file_sd_configs:
    - files: ['targets/*.json']
